import React, {useEffect, useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Router from 'next/router'
import axios from 'axios'
import styles from '../styles/styles.module.scss'
import Layout3 from '../components/Layout3/Layout3'
import FormBox from '../components/FormBox/FormBox'
import InputField from '../components/InputField/InputField'
import Button from '../components/Button/Button'

export default function Login(){

  const [error, setError] = useState("")
  const [data, setData] = useState({
    email:"", password:""
  })

  useEffect(() => {
    const user_data = JSON.parse(localStorage.getItem("user_data"))
    async function getDetails(){
      try{
        let resData = await axios.get(`http://localhost:3501/api/account/${user_data.id}`)
        if(resData.status === 200) return Router.push('/')
      }catch(error){
        localStorage.removeItem("user_data")
        Router.push('/login')
      }
    }
    getDetails()
  },[])

  return (
    <>
      <Head>
        <title>Whatmovie | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout3>
        <FormBox title="Login">
          <InputField title="Email" type="email" id="email" value={data.email} placeholder="Enter your email" onHandle={onSave}/>
          <InputField title="Password" type="password" id="password" value={data.password} placeholder="Enter your password" onHandle={onSave}/>
          <p className={styles.error} id="error">{error}</p>
          <Button onHandle={onSubmit}>
            Submit
          </Button>
          <p className={styles.link}>Need an account ? <Link href="/register">Register</Link></p>
        </FormBox>
      </Layout3>
    </>
  )

  function onSave(event){
    setData(prevState => {
      return {...prevState, [event.target.id]:event.target.value}
    })
  }

  async function onSubmit() {
    try{
      let resData = await axios.post('http://localhost:3501/api/auth',data)
      localStorage.setItem("user_data", JSON.stringify(resData.data))
      Router.push('/')
    }catch(error){
      console.error(error)
      setError("Email or Password is incorrect")
    }
  }
}