import React, { useState, useEffect, useRef } from "react";
import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import { v4 as uuidv4 } from "uuid";
import Layout2 from "../components/Layout2/Layout2";
import Filter from "../components/Filter/Filter";
import axios from "axios";
import Movie from "./components/Movie";
import Youtube from "react-youtube";
import AppBar2 from "../components/AppBar2/AppBar2";
import ReactLoading from 'react-loading';
import Sidebar from "../components/Sidebar/Sidebar";

export default function Account() {
  return (
    <>
      <Head>
        <title>Whatmovie | Payment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar2/>
      <Layout2>
        <Sidebar/>
      </Layout2>
    </>
  );
}