import Head from 'next/head'
import Image from 'next/image'
import React, {useEffect, useState} from 'react'
import Link from 'next/link'
import Router from 'next/router'
import axios from 'axios'
import styles from '../styles/styles.module.scss'
import Layout3 from '../components/Layout3/Layout3'
import FormBox from '../components/FormBox/FormBox'
import InputField from '../components/InputField/InputField'
import Button from '../components/Button/Button'
import Swal from 'sweetalert2'

export default function Register() {

  const [error, setError] = useState("")
  const [data, setData] = useState({
    email:"",name:"",password:"",passwordConfirm:""
  })

  useEffect(() => {
    const user_data = JSON.parse(localStorage.getItem("user_data"))
    async function getDetails(){
      try{
        let resData = await axios.get(`http://localhost:3501/api/account/${user_data.id}`)
        if(resData.status === 200) return Router.push('/')
      }catch(error){
        localStorage.removeItem("user_data")
        Router.push('/register')
      }
    }
    getDetails()
  },[])

  return (
    <>
      <Head>
        <title>Whatmovie | Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout3>
        <FormBox title="Register">
          <InputField title="Email" type="email" id="email" value={data.email} placeholder="Enter your email" onHandle={onSave}/>
          <InputField title="Name" type="text" id="name" value={data.name} placeholder="Enter your name" onHandle={onSave}/>
          <InputField title="Password" type="password" id="password" value={data.password} placeholder="Enter your password" onHandle={onSave}/>
          <InputField title="Confirm Password" type="password" id="passwordConfirm" value={data.passwordConfirm} placeholder="Confirm password" onHandle={onSave}/>
          <p className={styles.error} id="error">{error}</p>
          <Button onHandle={onSubmit}>
            Submit
          </Button>
          <p className={styles.link}>Already have account ? <Link href="/login">Login</Link></p>
        </FormBox>
      </Layout3>
    </>
  )

  function onSave(event){
    setData(prevState => {
      return {...prevState, [event.target.id]:event.target.value}
    })
  }

  async function onSubmit(){
    if(Object.keys(data).some((key) => data[key] === "")){
      setError("Please enter a field")
    }else if(data.password != data.passwordConfirm){
      setError("Please enter a same password")
    }else{
      try{
        let resData = await axios.post('http://localhost:3501/api/account',data)
        setError("")
        Swal.fire({
          title: 'Success!',
          text: `You account already created`,
          icon: `success`,
          confirmButtonText: 'OK'
        }).then(function(){
          Router.push('/login')
        });
      }catch(error){
        setError("Email is Already in use")
      }
    }
  }
}