# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from TimeTable import Ui_TimeTablePage
from Register import Ui_RegisterPage
import sys

class Ui_LoginPage(object):
    def showMsgBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()
    def timeTablePageShow(self):
        self.TimeTablePage = QtWidgets.QMainWindow()
        self.ui = Ui_TimeTablePage()
        self.ui.setupUi(self.TimeTablePage)
        self.TimeTablePage.show()
        LoginPage.hide()
        
    def registerShow(self):
        self.registerWindow = QtWidgets.QMainWindow()
        self.ui = Ui_RegisterPage()
        self.ui.setupUi(self.registerWindow)
        self.registerWindow.show()
        
    def loginCheck(self):
        username = self.username_txt.text()
        password = self.password_txt.text()
        
        connection = sqlite3.connect("login.db")
        result = connection.execute("SELECT * FROM USERS WHERE USERNAME = ? AND PASSWORD = ?",(username,password))
        if(len(result.fetchall()) > 0):
            self.timeTablePageShow()
        else:
            self.showMsgBox('Warning','Invalid Username and Password')

    def registerCheck(self):
        self.registerShow()
    
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.setWindowModality(QtCore.Qt.NonModal)
        LoginPage.resize(400, 300)
        LoginPage.setMinimumSize(QtCore.QSize(400, 300))
        LoginPage.setMaximumSize(QtCore.QSize(400, 300))
        LoginPage.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        LoginPage.setFont(font)
        LoginPage.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/TimeTableIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginPage.setWindowIcon(icon)
        LoginPage.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(LoginPage)
        self.centralwidget.setObjectName("centralwidget")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(50, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(50, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.username_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.username_txt.setGeometry(QtCore.QRect(140, 70, 211, 22))
        self.username_txt.setObjectName("username_txt")
        self.password_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.password_txt.setGeometry(QtCore.QRect(140, 120, 211, 22))
        self.password_txt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_txt.setObjectName("password_txt")
        self.submit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.submit_btn.setGeometry(QtCore.QRect(260, 170, 93, 28))
        self.submit_btn.setObjectName("submit_btn")
        
        self.submit_btn.clicked.connect(self.loginCheck)
        
        self.register_btn = QtWidgets.QPushButton(self.centralwidget)
        self.register_btn.setGeometry(QtCore.QRect(260, 210, 93, 28))
        self.register_btn.setObjectName("register_btn")
        
        self.register_btn.clicked.connect(self.registerCheck)
        
        LoginPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        LoginPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginPage)
        self.statusbar.setObjectName("statusbar")
        LoginPage.setStatusBar(self.statusbar)

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "Login"))
        self.username_label.setText(_translate("LoginPage", "Username"))
        self.password_label.setText(_translate("LoginPage", "Password"))
        self.submit_btn.setText(_translate("LoginPage", "Submit"))
        self.register_btn.setText(_translate("LoginPage", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginPage = QtWidgets.QMainWindow()
    ui = Ui_LoginPage()
    ui.setupUi(LoginPage)
    LoginPage.show()
    sys.exit(app.exec_())
