# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import sys

class Ui_RegisterPage(object):
    def insertData(self):
        name = self.name_txt.text()
        username = self.username_txt.text()
        password = self.password_txt.text()
        
        connection = sqlite3.connect("login.db")
        connection.execute("INSERT INTO USERS VALUES(?,?)",(username,password))
        connection.commit()
        connection.close()
        
        with open("name.txt",mode='w') as f:
            f.write(name)
        
    def setupUi(self, RegisterPage):
        RegisterPage.setObjectName("RegisterPage")
        RegisterPage.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/TimeTableIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RegisterPage.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(RegisterPage)
        self.centralwidget.setObjectName("centralwidget")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(20, 50, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        RegisterPage.setMinimumSize(QtCore.QSize(400, 300))
        RegisterPage.setMaximumSize(QtCore.QSize(400, 300))
        RegisterPage.setSizeIncrement(QtCore.QSize(0, 0))
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(20, 100, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(20, 150, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.name_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.name_txt.setGeometry(QtCore.QRect(110, 50, 241, 22))
        self.name_txt.setObjectName("name_txt")
        self.username_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.username_txt.setGeometry(QtCore.QRect(110, 100, 241, 22))
        self.username_txt.setObjectName("username_txt")
        self.password_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.password_txt.setGeometry(QtCore.QRect(110, 150, 241, 22))
        self.password_txt.setObjectName("password_txt")
        self.submit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.submit_btn.setGeometry(QtCore.QRect(260, 200, 93, 28))
        self.submit_btn.setObjectName("submit_btn")
        
        self.submit_btn.clicked.connect(self.insertData)
        
        RegisterPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegisterPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        RegisterPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RegisterPage)
        self.statusbar.setObjectName("statusbar")
        RegisterPage.setStatusBar(self.statusbar)

        self.retranslateUi(RegisterPage)
        QtCore.QMetaObject.connectSlotsByName(RegisterPage)

    def retranslateUi(self, RegisterPage):
        _translate = QtCore.QCoreApplication.translate
        RegisterPage.setWindowTitle(_translate("RegisterPage", "Register"))
        self.name_label.setText(_translate("RegisterPage", "Name"))
        self.username_label.setText(_translate("RegisterPage", "Username"))
        self.password_label.setText(_translate("RegisterPage", "Password"))
        self.submit_btn.setText(_translate("RegisterPage", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterPage = QtWidgets.QMainWindow()
    ui = Ui_RegisterPage()
    ui.setupUi(RegisterPage)
    RegisterPage.show()
    sys.exit(app.exec_())
