# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeTablePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys , csv , os

class Ui_TimeTablePage(object):
    def __init__(self):
        self.items = 0
        
    def open_sheet(self):
        path = QtWidgets.QFileDialog.getOpenFileName(None, 'Open CSV', os.getenv('HOME'), 'CSV(*.csv)')
        if path[0] != '':
            with open(path[0], newline='') as csv_file:
                self.table.setRowCount(0)
                self.table.setColumnCount(4)
                my_file = csv.reader(csv_file)
                for row_data in my_file:
                    row = self.table.rowCount()
                    self.table.insertRow(row)
                    if len(row_data) > 0:
                        self.table.setColumnCount(len(row_data))
                    for column, stuff in enumerate(row_data):
                        item = QtWidgets.QTableWidgetItem(stuff)
                        self.table.setItem(row, column, item)
        
    def save_sheet(self):
        path = QtWidgets.QFileDialog.getSaveFileName(None, 'Save CSV', os.getenv('HOME'), 'CSV(*.csv)')
        if path[0] != '':
            with open(path[0], 'w',newline='') as csv_file:
                writer = csv.writer(csv_file, dialect='excel')
                for row in range(self.table.rowCount()):
                    row_data = []
                    for column in range(self.table.columnCount()):
                        item = self.table.item(row, column)
                        if item is not None:
                            row_data.append(item.text())
                        else:
                            row_data.append('')
                    writer.writerow(row_data)
        
    def add_entry(self):
        toDoList = self.insert_txt.text()
        date_add = self.date.text()
        time_add = self.time.text()
        
        try:
            toDoListItem = QtWidgets.QTableWidgetItem(toDoList)
            date_addItem = QtWidgets.QTableWidgetItem(date_add)
            time_addItem = QtWidgets.QTableWidgetItem(time_add)
            

            self.table.insertRow(self.items)
            self.table.setItem(self.items,0,date_addItem)
            self.table.setItem(self.items,1,time_addItem)
            self.table.setItem(self.items,2,toDoListItem)
            self.items += 1
            
            self.insert_txt.setText('')
            
        except ValueError:
            pass
                
    def reset_table(self):
        self.table.setRowCount(0)
        self.items = 0
    
    def setupUi(self, TimeTablePage):
        TimeTablePage.setObjectName("TimeTablePage")
        TimeTablePage.resize(800, 600)
        TimeTablePage.setMinimumSize(QtCore.QSize(800, 600))
        TimeTablePage.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/Image/TimeTableIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TimeTablePage.setWindowIcon(icon)
        TimeTablePage.setStyleSheet("")
        TimeTablePage.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(TimeTablePage)
        self.centralwidget.setObjectName("centralwidget")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(30, 5, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.date = QtWidgets.QDateEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(30, 440, 110, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date.setFont(font)
        self.date.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.date.setCalendarPopup(True)
        self.date.setTimeSpec(QtCore.Qt.LocalTime)
        self.date.setDate(QtCore.QDate.currentDate())
        self.date.setObjectName("date_inp")
        self.time = QtWidgets.QTimeEdit(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(30, 490, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.time.setFont(font)
        self.time.setTabletTracking(True)
        self.time.setAcceptDrops(False)
        self.time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.time.setCalendarPopup(False)
        self.time.setObjectName("time_inp")
        self.time.setTime(QtCore.QTime.currentTime())
        
        self.insert_btn = QtWidgets.QPushButton(self.centralwidget)
        self.insert_btn.setGeometry(QtCore.QRect(660, 290, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.insert_btn.setFont(font)
        self.insert_btn.setObjectName("insert_btn")
        
        self.insert_btn.clicked.connect(self.add_entry)
        
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(660, 360, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clear_btn.setFont(font)
        self.clear_btn.setObjectName("clear_btn")
        
        self.clear_btn.clicked.connect(self.reset_table)
        
        self.opn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.opn_btn.setGeometry(QtCore.QRect(660, 420, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.opn_btn.setFont(font)
        self.opn_btn.setObjectName("opn_btn")
        
        self.opn_btn.clicked.connect(self.open_sheet)
        
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(660, 480, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        
        self.save_btn.clicked.connect(self.save_sheet)
        
        self.insert_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.insert_txt.setGeometry(QtCore.QRect(200, 430, 431, 91))
        self.insert_txt.setStyleSheet("")
        self.insert_txt.setObjectName("insert_txt")
        self.logo = QtWidgets.QWidget(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(640, 50, 151, 151))
        self.logo.setStyleSheet("image: url(:/image/Image/TimeTableLogo.png);")
        self.logo.setObjectName("logo")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(30, 50, 601, 361))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setMinimumSize(QtCore.QSize(601, 361))
        self.table.setMaximumSize(QtCore.QSize(601, 361))
        self.table.setSizeIncrement(QtCore.QSize(0, 0))
        self.table.setGridStyle(QtCore.Qt.SolidLine)
        
        self.table.setColumnCount(4)
        
        header = self.table.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        
        self.table.setObjectName("table")
        
        self.table.setRowCount(0)
        
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.table.horizontalHeader().setDefaultSectionSize(147)
        self.table.horizontalHeader().setHighlightSections(True)
        self.table.horizontalHeader().setStretchLastSection(True)
        TimeTablePage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TimeTablePage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        TimeTablePage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TimeTablePage)
        self.statusbar.setObjectName("statusbar")
        TimeTablePage.setStatusBar(self.statusbar)

        self.retranslateUi(TimeTablePage)
        QtCore.QMetaObject.connectSlotsByName(TimeTablePage)
        

    def retranslateUi(self, TimeTablePage):
        _translate = QtCore.QCoreApplication.translate
        TimeTablePage.setWindowTitle(_translate("TimeTablePage", "Time Table"))
        self.insert_btn.setText(_translate("TimeTablePage", "Insert"))
        self.clear_btn.setText(_translate("TimeTablePage", "Clear"))
        self.save_btn.setText(_translate("TimeTablePage", "Save"))
        self.opn_btn.setText(_translate("TimeTablePage", "Open"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("TimeTablePage", "Date"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("TimeTablePage", "Time"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("TimeTablePage", "To Do List"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("TimeTablePage", "Result"))
        with open("name.txt",mode='r') as f:
            namefromf = f.read()
            self.name_label.setText(_translate("TimeTablePage", "Name : "+namefromf))
import MyResource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TimeTablePage = QtWidgets.QMainWindow()
    ui = Ui_TimeTablePage()
    ui.setupUi(TimeTablePage)
    TimeTablePage.show()
    sys.exit(app.exec_())